//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiHouseFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consignment()
        {
            this.Item_Consignment = new HashSet<Item_Consignment>();
        }
    
        public int id { get; set; }
        public Nullable<int> warehouseId { get; set; }
        public string supplier { get; set; }
        public Nullable<int> totalItems { get; set; }
        public Nullable<System.DateTime> arrivalDate { get; set; }
        public string consignmentName { get; set; }
        public string instruction { get; set; }
        public string consignmentStatus { get; set; }
        public string shelfInserted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Consignment> Item_Consignment { get; set; }
    }
}
