//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiHouseFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int id { get; set; }
        public string fullName { get; set; }
        public string organizationName { get; set; }
        public string selectedWarehouse { get; set; }
        public string organizationAddress { get; set; }
        public string contact { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string email { get; set; }
    }
}
