//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiHouseFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.item_Order = new HashSet<item_Order>();
        }
    
        public int orderId { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public string orderStatus { get; set; }
        public Nullable<int> warehouseId { get; set; }
        public Nullable<int> totalOrderQuanitity { get; set; }
        public string instruction { get; set; }
        public Nullable<int> dispatchNo { get; set; }
        public string shelfRetrieval { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_Order> item_Order { get; set; }
    }
}
