//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiHouseFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shelf
    {
        public int id { get; set; }
        public string shelfName { get; set; }
        public Nullable<int> warehouse_id { get; set; }
        public string zone { get; set; }
        public string shelfItems { get; set; }
        public Nullable<int> slotsRemaining { get; set; }
    }
}
