//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiHouseFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int id { get; set; }
        public int itemId { get; set; }
        public Nullable<int> warehouseId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> shelfId { get; set; }
        public Nullable<int> slotNumber { get; set; }
        public Nullable<System.DateTime> transactionDate { get; set; }
    }
}
