//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiHouseFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Warehouse()
        {
            this.Item_Warehouse = new HashSet<Item_Warehouse>();
        }
    
        public int id { get; set; }
        public byte[] warehouseHTML { get; set; }
        public Nullable<double> actualWarehouseWidth { get; set; }
        public Nullable<double> actualWarehouseLength { get; set; }
        public Nullable<double> scaledWarehouseWidth { get; set; }
        public Nullable<double> scaledWarehouseLength { get; set; }
        public Nullable<double> actualShelfHeight { get; set; }
        public Nullable<double> actualShelfWidth { get; set; }
        public Nullable<int> actualShelfLength { get; set; }
        public Nullable<double> scaledShelfWidth { get; set; }
        public Nullable<double> scaledShelfLength { get; set; }
        public Nullable<int> shelves { get; set; }
        public Nullable<int> shelfRows { get; set; }
        public Nullable<int> shelfSlots { get; set; }
        public Nullable<int> managerId { get; set; }
        public Nullable<int> sections { get; set; }
        public string warehouseName { get; set; }
        public string warehouseAddress { get; set; }
        public string warehouseLogo { get; set; }
        public string country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Warehouse> Item_Warehouse { get; set; }
    }
}
